import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Insight, InsightResponse } from '../types/insight'

const Home: NextPage = () => {

  const [insight, setInsight] = useState<Insight>()

  useEffect(() => {
    async function init() {
      const response = await fetch('/api/insight');
      const responseJson = (await response.json()) as InsightResponse
      setInsight(responseJson.insight)
    }
    init()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      {insight && 
      <p className={styles.description}>
        <h3>Top influencers per category by followers</h3>
        {Object.keys(insight.topInfluencersPerCategoryByFollowers).map((category) => {
          return <div key={category}>
            Category: {category},
            Influencer: {insight.topInfluencersPerCategoryByFollowers[category].name},
            Followers: {insight.topInfluencersPerCategoryByFollowers[category].value}
          </div>
        })}
        <h3>Top influencers per country by engagement avg</h3>
        {Object.keys(insight.topInfluencersPerCountryByEngagementAvg).map((country) => {
          return <div key={country}>
            Country: {country},
            Influencer: {insight.topInfluencersPerCountryByEngagementAvg[country].name},
            Followers: {insight.topInfluencersPerCountryByEngagementAvg[country].value}
          </div>
        })}
      </p>}

      </main>
    </div>
  )
}

export default Home
